# Generated by Django 4.1.2 on 2022-11-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoteBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='NoteBook Name')),
                ('img', models.ImageField(upload_to='media', verbose_name='NoteBook Image')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('placeforlink', models.URLField(default=None, max_length=500, verbose_name='Add Url')),
                ('description', models.TextField(verbose_name='Description')),
                ('slug', models.SlugField(default=None, unique=True, verbose_name='NoteBook Slug')),
            ],
            options={
                'verbose_name': 'NoteBook',
                'verbose_name_plural': 'NoteBooks',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Phone Name')),
                ('img', models.ImageField(upload_to='media', verbose_name='Phone Image')),
                ('price', models.IntegerField(blank=True, default=None, verbose_name='Price')),
                ('placeforlink', models.URLField(default=None, max_length=500, verbose_name='Add Url')),
                ('description', models.TextField(verbose_name='Description')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Phone Slug')),
            ],
            options={
                'verbose_name': 'Phone',
                'verbose_name_plural': 'Phones',
            },
        ),
    ]
