# Generated by Django 4.1.3 on 2022-11-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='placeforlink',
            field=models.URLField(verbose_name='Add Url'),
        ),
    ]
