# Generated by Django 4.1.3 on 2022-11-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_phone_placeforlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='placeforlink',
            field=models.URLField(verbose_name='Add Url'),
        ),
    ]
